### ISSUE TITLE
Criar tabela interna para segmentação de serviços por estados

### ISSUE THREAD

**Issue by osintbrazuca** [osintbrazuca/osint-brazuca#12]
Criar uma tabela em cada sessão separando  serviços por estados

E o estado em questão deve ser clicável direcionando o usuário para sua segmentação dentro de **Categorias por Estados Brasileiros**
- https://github.com/osintbrazuca/OSINT-Brazuca#categorias-por-estados-brasileiros---em-constru%C3%A7%C3%A3o

# Exemplo:

### Titulo do serviço
Descrição
- www.link_01.com.br

### Titulo do serviço 02
Descrição exemplo do serviço segmentado em estados
       <details>
        <summary>Serviço por estado</summary>
| AC  |  AL  | AM  |  AP  |BA  |CE  |DF  |ES  |GO  |MA  |MG |MS  |MT| TO|
| ------------------- | ------------------- |------------------- |------------------- |------------------- |------------------- |------------------- |------------------- |------------------- |------------------- |------------------- |------------------- |------------------- |------------------- |
| PA |  PB  | PE  |  PI  |PR  |RJ |RN  |RO |RR  |RS  |SC  |SE  |SP|..|

</details>

**Comment by fellipematos** [comment]
Segue um modelo de exemplo, caso queria adicionar no projeto.

```
| Status | Sigla | Estado |  |
|--|--|--|--|
|🔴|AC|Acre||
|🔴|AL|Alagoas||
|🔴|AP|Amapá||
|🔴|AM|Amazonas||
|🔴|BA|Bahia||
|🔴|CE|Ceará||
|🔴|DF|Distrito Federal||
|🔴|ES|Espírito Santo||
|🔴|GO|Goiás||
|🔴|MA|Maranhão||
|🔴|MG|Mato Grosso||
|🔴|MS|Mato Grosso do Sul||
|🔴|MG|Minas Gerais||
|🔴|PA|Pará||
|🔴|PB|Paraíba||
|🔴|PR|Paraná||
|🔴|PE|Pernambuco||
|🔴|PI|Piauí||
|🔴|RJ|Rio de Janeiro||
|🔴|RN|Rio Grande do Norte||
|🔴|RS|Rio Grande do Sul||
|🔴|RO|Rondônia||
|🔴|RR|Roraima||
|🔴|SC|Santa Catarina||
|🟢|SP|São Paulo|[Acesso]()|
|🔴|SE|Sergipe||
|🔴|TO|Tocantins||
```

Resultado 

| Status | Sigla | Estado |  |
|--|--|--|--|
|🔴|AC|Acre||
|🔴|AL|Alagoas||
|🔴|AP|Amapá||
|🔴|AM|Amazonas||
|🔴|BA|Bahia||
|🔴|CE|Ceará||
|🔴|DF|Distrito Federal||
|🔴|ES|Espírito Santo||
|🔴|GO|Goiás||
|🔴|MA|Maranhão||
|🔴|MG|Mato Grosso||
|🔴|MS|Mato Grosso do Sul||
|🔴|MG|Minas Gerais||
|🔴|PA|Pará||
|🔴|PB|Paraíba||
|🔴|PR|Paraná||
|🔴|PE|Pernambuco||
|🔴|PI|Piauí||
|🔴|RJ|Rio de Janeiro||
|🔴|RN|Rio Grande do Norte||
|🔴|RS|Rio Grande do Sul||
|🔴|RO|Rondônia||
|🔴|RR|Roraima||
|🔴|SC|Santa Catarina||
|🟢|SP|São Paulo|[Acesso]()|
|🔴|SE|Sergipe||
|🔴|TO|Tocantins||

**Comment by MrCl0wnLab** [comment]
Obrigado @fellipematos ,
Esse modelo já pode funcionar, agora estamos analisando a migração para PAGE e depois implementar algo semelhante a sua ideia.

vlw pela contribuição.
