### ISSUE TITLE
Solicitação  de parceria  com blackdogosint 

### ISSUE THREAD

**Issue by darkcode357** [osintbrazuca/OSINT-Brazuca#18]
Opa eae pessoal so brazuca  blz, me chamo Luiz e sou um dev Master do blackdogosint  uma biblioteca  em python para extrair  e correlacionar  dados da Internet, achei bem interessante  a ideia de vocês de fazer algo voltado para o Brasil  e gostaria de juntar os dois projetos, vocês com a informação  de código aberto e eu com a parte de automação, aguardo  contato 

Telegram  darkcode0x00 
Segue a baixo a lista de issues aberta para o projeto https://github.com/darkcode357/blackdogosint/issues

Segue o link do projeto https://github.com/darkcode357/blackdogosint

**Comment by MrCl0wnLab** [comment]
Obrigado,
Você pode usar o repo como fonte de conhecimento.
