### ISSUE TITLE
Cadastro Nacional dos Advogados (CNA)

### ISSUE THREAD

**Issue by leandroramosarq** [osintbrazuca/OSINT-Brazuca#22]
Pesquisar no Repositório do cadastro de todos os advogados do Brasil.

- Mantido pelo Conselho Federal da OAB, que exerce a função de repositório do cadastro de todos os advogados do Brasil. Para realizar a consulta, basta preencher o formulário e pesquisar. (Nome; Nº da inscrição; Seccional; Tipo de inscrição)

- https://cna.oab.org.br

![imagem_2021-08-25_130054](https://user-images.githubusercontent.com/80374188/130824972-c675a0be-bba4-474e-a8e2-da3b1bc5cecd.png)

**Comment by osintbrazuca** [comment]
## Obrigado pela contribuição:
> https://github.com/osintbrazuca/OSINT-Brazuca/commit/dfe1a51d0d634b6d6eca6051adf1f4286ed68510
