### ISSUE TITLE
Adicionar consulta de licenças ao tópico aeroviário

### ISSUE THREAD

**Issue by gabrieltetz** [osintbrazuca/osint-brazuca#33]
### Consulta de Licença Aeronáutica (CHT)
Todos os tripulantes civis brasileiros devem ser registrados na ANAC. Sendo validado o registro pelo seu Código Anac (CANAC).
- https://sistemas.anac.gov.br/consultadelicencas/

**Comment by MrCl0wnLab** [comment]
Obrigado pela contribuição vamos adicionar .
Em sua próxima contribuição por gentilizar usar PR.

**Comment by MrCl0wnLab** [comment]
Done!
- https://github.com/osintbrazuca/osint-brazuca/commit/249129406cff1fe1fbd1ef43aed6c9ff933c9ecb
