### ISSUE TITLE
Citar/adicionar ferramenta que realiza a busca de projetos no sistema da ANCINE

### ISSUE THREAD

**Issue by takusuman** [osintbrazuca/osint-brazuca#34]
Há uns meses (bota "meses" nisso), eu fiz uma ferramenta ridiculamente simples que busca por registros de uma produtora no Sistema ANCINE Digital (S.A.D.) chamada Harpya.
https://github.com/takusuman/harpya
Quando vi esse repositório, acreditei que talvez se encaixasse aqui.
É uma ferramenta bem simples, repito, então talvez vocês até desejem criar um fork para consertar ou adicionar recursos novos.
Agradeço pela atenção.

**Comment by MrCl0wnLab** [comment]
Obrigado pela contribuição amigo, vamos colocar um label segmentando o projeto para nosso repo de tools futuras.
Hoje o repo principal é focado em URLS somente.
