### ISSUE TITLE
Consulta de Portabilidade

### ISSUE THREAD

**Issue by Romullo** [osintbrazuca/osint-brazuca#40]
Consulta de portabilidade de números celulares e fixos
https://consultanumero.abrtelecom.com.br/consultanumero/consulta/consultaHistoricoRecenteCtg

**Comment by MrCl0wnLab** [comment]
Olá @Romullo ,
Obrigado pela informação!

A URL foi adicionada:
- https://github.com/osintbrazuca/osint-brazuca/commit/68325fbe234c2cf73c02cd06d7623eaef88d9da2
