### ISSUE TITLE
Pesquisar por cpf/codigo identificação servidor do IBGE.

### ISSUE THREAD

**Issue by lucaslamdev** [osintbrazuca/osint-brazuca#42]
https://respondendo.ibge.gov.br/verifique-a-identidade-do-entrevistador.html
https://www.ibge.gov.br/acesso-informacao/institucional/documentos-ibge/1861-novo-portal/institucional/17422-servidores.html

Retorna diversos dados sobre o servidor.

**Comment by MrCl0wnLab** [comment]
Olá @lucaslamdev ,
Obrigado pela contribuição.

Adicionamos a informação:
- https://github.com/osintbrazuca/osint-brazuca/commit/e54cc8f62235b8aedff0bcd78dcfdd3be1b0b952
