### ISSUE TITLE
Consultar e identificar frequências de rádios entre muitas outras

### ISSUE THREAD

**Issue by opastorello** [osintbrazuca/osint-brazuca#43]
Atenção: melhor usar o browser Internet Explorer ou Firefox e permitir que os mesmos aceitem os Cookies do site da ANATEL.

https://sistemas.anatel.gov.br/stel/Consultas/RecuperacaoFrequencias/tela.asp?SISQSmodulo=9896

1- Abrirá uma página para preenchimento, preencha da seguinte forma:
2- Em recuperação de dados: marque UF;
3- Em apresentar dados por: marque a letra J (frequência e entidade) em faixa de frequência: coloque a frequência que deseja scanear, ex.: inicial: 450,000 final: 460,000 (NÃO ESQUEÇA DA VÍRGULA) OBS: não de um espaço de frequencia muito largo,as vezes dá erro na pesquisa;
4- Em unidade coloque MHZ nos dois;
5- Em sigla da UF: coloque a sigla do seu estado
6- Em serviço inicial e serviço final nao coloque nada, deixe do jeito que está em grupo de estações: marque todos (consolidado);
7- Agora clique abaixo em exportar excel e salve o arquivo em seu micro;
- Listagem muito grande de amplo espectro demoram para serem processadas e podem travar. Recomenda-se utilizar espectro pequeno de frequências por UF exemplo: 160,000 a 170,000;
Divirtam-se!!!

**Comment by MrCl0wnLab** [comment]
Olá @opastorello ,
Obrigado pela informações

A URL foi adicionada
- https://github.com/osintbrazuca/osint-brazuca/commit/88bc780d8d95f4889cdab31abe859b1d7b302aec
