### ISSUE TITLE
Consultar socios de empresas do estado de São Paulo

### ISSUE THREAD

**Issue by cai0ferragut** [osintbrazuca/osint-brazuca#46]
Boa noite, gostaria de sugerir a inclusão do Site da Jucesp (Junta Comercial do Estado de São Paulo.)

Nela com um login unificado do governo do estado de SP (mesmo da consulta de NFe) é possivel ter acesso na INTEGRA do contrato social de qualquer empresa do estado!

Segue o link.
https://www.jucesponline.sp.gov.br/

Estou a disposição para ajudar com prints ou vídeos de como fazer

O que acha?

**Comment by MrCl0wnLab** [comment]
Olá @cai0ferragut ,
**obrigado pela contribuição.**

Analisei a URL postada e ele tem alguns ações que é possível consultar diretamente
Exemplo:
- https://www.jucesponline.sp.gov.br/Pre_Visualiza.aspx?nire=35300016831&idproduto=

Em nosso próximo PR da readme vamos add a URL e tricks internas.

**Comment by MrCl0wnLab** [comment]
Olá @cai0ferragut ,
Obrigado pela informação!

Adicionamos:
- https://github.com/osintbrazuca/osint-brazuca/commit/37010a55ba1f247aa90d7cc5cd0565c939e170ba
