### ISSUE TITLE
Nova Consulta de Antecedente Criminal

### ISSUE THREAD

**Issue by artYYDP** [osintbrazuca/osint-brazuca#50]
Novo site: https://antecedentes.dpf.gov.br/antecedentes-criminais/certidao

Correção do texto: a consulta existente é do site do Pará, e não do Paraná como está escrito.

**Comment by MrCl0wnLab** [comment]
Obrigado, vamos add em nosso PR.

**Comment by MrCl0wnLab** [comment]
Olá @artYYDP , 
O site está offline.
Você tem alguma versão atual?
